spring.application.name=order-processing-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/orderplatform
spring.datasource.username=orderapp
spring.datasource.password=devpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=c3ByaW5nYm9vdC1vcmRlci1wcm9jZXNzaW5nLXBsYXRmb3JtLXNlY3JldC1rZXktY2hhbmdlLW1l
jwt.expiration-ms=3600000